# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Movement.create(name:'Air Squat', description: "Keeping chest upright send hips back as if going to sit on a chair. Squat until you are just below parallel", equipment: 'Body weight')
# Movement.create(name:'Back Squat', description:"Same as air squat but with weight", equipment:"Barbell and weight if needed")
# Movement.create(name:'(Medicine) Ball Slams')
# Movement.create(name:'Barbell Snatch')
# Movement.create(name:'Box Jump')
# Movement.create(name:'Burbee Box Jumps')
# Movement.create(name:'Burbees')
# Movement.create(name:'Clean & Jerk')
# Movement.create(name:'Dip (rings)')
# Movement.create(name:'Double-Unders')
# Movement.create(name:'Dumbbell Snatch')
# Movement.create(name:'Dumbbell Clean')
# Movement.create(name:'Dumbbell Clean & Jerk')
# Movement.create(name:'Front Squat')
# Movement.create(name:'Farmers Carry')
# Movement.create(name:'Glute-Ham Sit-up')
# Movement.create(name:'Handstand Hold')
# Movement.create(name:'Handstand Walk')
# Movement.create(name:'Handstand Push-up(HSPU)')
# Movement.create(name:'Handstand(self assist')
# Movement.create(name:'Hang Clean')
# Movement.create(name:'Hang Power Clean')
# Movement.create(name:'Hang Snatch')
# Movement.create(name:'Hang Snatch Balance')
# Movement.create(name:'Heaving Snatch Balance')
# Movement.create(name:'Hollow Rocks')
# Movement.create(name:'Jerk')
# Movement.create(name:'Jump Squat')
# Movement.create(name:'Jumping Pull-Ups')
# Movement.create(name:'Kettlebell Swings')
# Movement.create(name:'Kettlebell Snatch')
# Movement.create(name:'Kettlebell Clean')
# Movement.create(name:'Kettlebell Push-Jerk')
# Movement.create(name:'Kettlebell Press')
# Movement.create(name:'Kipping Pull-Ups')
# Movement.create(name:'Knees to Elbows')
# Movement.create(name:'L sit')
# Movement.create(name:'Medicine Ball Clean')
# Movement.create(name:'Muscle-up(rings)')
# Movement.create(name:'Muscle-up(bar)')
# Movement.create(name:'Overhead Squat(OHS)')
# Movement.create(name:'Power Clean')
# Movement.create(name:'Power Snatch')
# Movement.create(name:'Pressing Snatch Balance')
# Movement.create(name:'Pull-Ups (strict)')
# Movement.create(name:'Push-Jerk')
# Movement.create(name:'Push-Press')
# Movement.create(name:'Push-Ups')
# Movement.create(name:'Rope Climb')
# Movement.create(name:'Row')
# Movement.create(name:'Sit-Ups')
# Movement.create(name:'Shoulder Press')
# Movement.create(name:'Snatch')
# Movement.create(name:'Snatch Balance')
# Movement.create(name:'Thruster')
# Movement.create(name:'Wall Balls')
# Movement.create(name:'Walking Lunges')
# Movement.create(name:'Weighted Pull-Ups')
# Movement.create(name:'200 Meter Run')
# Movement.create(name:'400 Meter Run')
# Movement.create(name:'800 Meter Run')
# Movement.create(name:'1 Mile Run')
# Movement.create(name:'200 Meter Row')
# Movement.create(name:'400 Meter Row')
# Movement.create(name:'800 Meter Row')
# Movement.create(name:'1 Mile Row')
